steps:
# basic funtionality test
- name: 'python:3.6'
  id: basic-test
  args:
    - python
    - ./integration_test/step_1.py
  env:
    - 'HOST=step_1'

# http2 test
- name: 'python:3.6'
  id: http2-test
  args:
    - python
    - ./integration_test/step_2.py

# local backup test
- name: 'python:3.6'
  id: local-backup-test
  args:
    - python
    - ./integration_test/step_3.py

# gcs backup test
- name: 'python:3.6'
  id: gcs-backup-test
  args:
    - python
    - ./integration_test/step_4.py

# publish
- name: 'python:3.6'
  id: publish
  args:
    - python
    - ./integration_test/publish.py
  waitFor:
    - basic-test
    - http2-test
    - local-backup-test
    - gcs-backup-test

timeout: 3000s
