steps:
- name: 'gcr.io/cloud-builders/git'
  id: clone-dcm4che
  args:
  - clone
  - https://github.com/dcm4che/dcm4che.git
  - dcm4che

- name: 'gcr.io/cloud-builders/git'
  id: checkout-dcm4che-tag
  args:
  - checkout
  - "tags/5.15.1"
  dir: dcm4che

- name: "maven:3.6.0-jdk-8"
  id: build-tools
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - bash
  - integration_test/mvn-install-tools.sh

- name: "maven:3.6.0-jdk-8"
  id: cstore-scp-run
  args:
  - bash
  - integration_test/run_store_scp_and_wait.sh
  - ${_STORE_SCP_RUN_STEP}
  - ${_STORE_SCP_PORT}
  - ${_CLOSE_STORE_SCP_PORT}

# run adapter, close when connection established on _CLOSE_ADAPTER_PORT
- name: 'gradle:5.4.1-jdk8'
  id: adapter-main
  args: [ 'bash', '../integration_test/run_adapter_and_wait.sh', '${_VERSION}', '${_PROJECT}', '${_LOCATION}', '${_DATASET}', '${_STORE_NAME}', '${_ADAPTER_PORT}', '${_CLOSE_ADAPTER_PORT}', '${_STORE_SCP_RUN_STEP}', '${_STORE_SCP_PORT}']
  dir: import
  waitFor: ['-']

# create dataset if not exists, re-create store (delete if exists, then create)
- name: 'google/cloud-sdk:250.0.0'
  id: setup-dataset-and-dicom-store
  args:
  - bash
  - integration_test/setup_dataset_and_store.sh
  - ${_PROJECT}
  - ${_LOCATION}
  - ${_DATASET}
  - ${_STORE_NAME}
  waitFor: ['-']

# busybox is a compact utility image
- name: 'busybox:latest'
  id: wait-for-adapter
  args:
  - ash
  - integration_test/wait_for_port.sh
  - ${_ADAPTER_RUN_STEP}
  - ${_ADAPTER_PORT}
  waitFor:
  - build-tools
  - setup-dataset-and-dicom-store

- name: 'busybox:latest'
  id: wait-for-storescp
  args:
  - ash
  - integration_test/wait_for_port.sh
  - ${_STORE_SCP_RUN_STEP}
  - ${_STORE_SCP_PORT}
  waitFor:
  - build-tools

- name: "maven:3.6.0-jdk-8"
  id: run-store-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.storescu.StoreSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} ../../../integration_test/example.dcm'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-storescu"
  waitFor:
  - wait-for-adapter

- name: "maven:3.6.0-jdk-8"
  id: run-find-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.findscu.FindSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -L IMAGE -X --out-cat --out-file findscu-result.xml --out-dir ../../../integration_test/'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-findscu"
  waitFor:
  - run-store-scu

- name: "maven:3.6.0-jdk-8"
  id: run-move-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.movescu.MoveSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} -m SOPInstanceUID=111 --dest STORESCP'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-movescu"
  waitFor:
  - run-find-scu
  - wait-for-storescp

- name: 'busybox:latest'
  id: close-adapter
  args:
  - nc
  - '-z'
  - ${_ADAPTER_RUN_STEP}
  - ${_CLOSE_ADAPTER_PORT}
  waitFor:
  - run-move-scu

- name: 'busybox:latest'
  id: close-store-scp
  args:
  - nc
  - '-z'
  - ${_STORE_SCP_RUN_STEP}
  - ${_CLOSE_STORE_SCP_PORT}
  waitFor:
  - run-move-scu

- name: 'google/cloud-sdk:250.0.0'
  id: check-store-curl
  args:
  - bash
  - integration_test/curl-dcm.sh
  - "https://healthcare.googleapis.com/${_VERSION}/projects/${_PROJECT}/locations/${_LOCATION}/datasets/${_DATASET}/dicomStores/${_STORE_NAME}/dicomWeb/studies/111/series/111/instances/111"
  - integration_test/downloaded.dcm
  waitFor:
  - run-store-scu

- name: 'busybox:latest'
  id: check-store-diff
  args:
  - diff
  - 'integration_test/downloaded.dcm'
  - 'integration_test/example.dcm'
  waitFor:
  - check-store-curl

- name: 'busybox:latest'
  id: check-find-diff
  args:
  - diff
  - 'integration_test/findscu-result1.xml'
  - 'integration_test/findscu-expected.xml'
  waitFor:
  - run-find-scu

# storescp adds 1 extra tag
- name: 'busybox:latest'
  id: check-move-diff
  args:
  - diff
  - 'integration_test/storescp-data/111'
  - 'integration_test/example-moved.dcm'
  waitFor:
  - run-move-scu

- name: 'google/cloud-sdk:250.0.0'
  id: delete-dicom-store
  args:
  - gcloud
  - alpha
  - healthcare
  - dicom-stores
  - delete
  - ${_STORE_NAME}
  - "--project=${_PROJECT}"
  - "--dataset=${_DATASET}"
  - "--location=${_LOCATION}"  
  - "--quiet"
  waitFor:
  - check-store-curl
  - run-find-scu
  - run-move-scu

substitutions:
  _VERSION: v1beta1
  _PROJECT: gcp-healthcare-oss-test
  _LOCATION: us-central1
  _DATASET: healthcare-dicom-dicomweb-adapter-test
  _STORE_NAME: integration-test-store
  _ADAPTER_PORT: '2575'
  _CLOSE_ADAPTER_PORT: '3000'
  _STORE_SCP_PORT: '2576'
  _CLOSE_STORE_SCP_PORT: '3001'
# Cloud build names containers that run steps: step_0, step_1 etc. These are also their dns names on docker network.
# Update to correct value if adding/removing steps before adapter run.
  _ADAPTER_RUN_STEP: 'step_4'
  _STORE_SCP_RUN_STEP: 'step_3'
