steps:
- name: 'gcr.io/cloud-builders/git'
  id: clone-dcm4che
  args:
  - clone
  - https://github.com/dcm4che/dcm4che.git
  - dcm4che

- name: 'gcr.io/cloud-builders/git'
  id: checkout-dcm4che-tag
  args:
  - checkout
  - "tags/5.15.1"
  dir: dcm4che

- name: "maven:3.6.0-jdk-8"
  id: build-store-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - install
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-storescu"

# run adapter, close when connection established on _CLOSE_ADAPTER_PORT
- name: 'gradle:5.4.1-jdk8'
  id: gradle-run-adapter
  args: [ 'bash', '../integration_test/run_adapter_and_wait.sh', '${_VERSION}', '${PROJECT_ID}', '${_LOCATION}', '${_DATASET}', '${_STORE_NAME}', '${_ADAPTER_PORT}', '${_CLOSE_ADAPTER_PORT}']
  dir: import
  waitFor: ['-']

# create dataset if not exists, re-create store (delete if exists, then create)
- name: 'google/cloud-sdk:250.0.0'
  id: setup-dataset-and-dicom-store
  args:
  - bash
  - integration_test/setup_dataset_and_store.sh
  - ${_LOCATION}
  - ${_DATASET}
  - ${_STORE_NAME}
  waitFor: ['-']

# busybox is a compact utility image
- name: 'busybox:latest'
  id: wait-for-adapter
  args:
  - ash
  - integration_test/wait_for_port.sh
  - ${_ADAPTER_RUN_STEP}
  - ${_ADAPTER_PORT}
  waitFor:
  - build-store-scu
  - setup-dataset-and-dicom-store

- name: "maven:3.6.0-jdk-8"
  id: run-store-scu
  volumes:
  - name: 'vol1'
    path: '/root/.m2'
  args:
  - mvn
  - 'exec:java'
  - '-Dexec.mainClass=org.dcm4che3.tool.storescu.StoreSCU'
  - '-Dexec.args=-c IMPORTADAPTER@${_ADAPTER_RUN_STEP}:${_ADAPTER_PORT} ../../../integration_test/example.dcm'
  dir: "dcm4che/dcm4che-tool/dcm4che-tool-storescu"
  waitFor:
  - wait-for-adapter

- name: 'busybox:latest'
  id: close-adapter
  args:
  - nc
  - '-z'
  - ${_ADAPTER_RUN_STEP}
  - ${_CLOSE_ADAPTER_PORT}
  waitFor:
  - run-store-scu

- name: 'google/cloud-sdk:250.0.0'
  id: curl-dcm
  args:
  - bash
  - integration_test/curl-dcm.sh
  - "https://healthcare.googleapis.com/${_VERSION}/projects/${PROJECT_ID}/locations/${_LOCATION}/datasets/${_DATASET}/dicomStores/${_STORE_NAME}/dicomWeb/studies/111/series/111/instances/111"
  - integration_test/downloaded.dcm
  waitFor:
  - run-store-scu

- name: 'busybox:latest'
  id: diff-dcm
  args:
  - diff
  - 'integration_test/downloaded.dcm'
  - 'integration_test/example.dcm'
  waitFor:
  - curl-dcm

- name: 'google/cloud-sdk:250.0.0'
  id: delete-dicom-store
  args:
  - gcloud
  - alpha
  - healthcare
  - dicom-stores
  - delete
  - ${_STORE_NAME}
  - "--dataset=${_DATASET}"
  - "--location=${_LOCATION}"  
  - "--quiet"
  waitFor:
  - diff-dcm

substitutions:
  _VERSION: v1beta1
  _LOCATION: europe-west2
  _DATASET: integration-test-dataset
  _STORE_NAME: integration-test-store
  _ADAPTER_PORT: '2575'
  _CLOSE_ADAPTER_PORT: '3000'
# Cloud build names containers that run steps: step_0, step_1 etc. These are also their dns names on docker network.
# Update to correct value if adding/removing steps before adapter run.
  _ADAPTER_RUN_STEP: 'step_3'
