steps:
# basic funtionality test
- name: 'python:3.6'
  id: basic-test
  args:
    - python
    - ./integration_test/step_1.py
  env:
    - 'HOST=step_1'

# http2 test
- name: 'python:3.6'
  id: http2-test
  args:
    - python
    - ./integration_test/step_2.py
  waitFor:
    - basic-test

# local backup test
- name: 'python:3.6'
  id: local-backup-test
  args:
    - python
    - ./integration_test/step_3.py
  waitFor:
    - http2-test

# gcs backup test
- name: 'python:3.6'
  id: gcs-backup-test
  args:
    - python
    - ./integration_test/step_4.py
  waitFor:
    - local-backup-test

timeout: 1800s
